add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 1
truncate_to_repo = false 
style = 'bold blue'
fish_style_pwd_dir_length = 1

[character]
success_symbol = '[❯](red)[❯](yellow)[❯](green)' 
error_symbol = '[✖](red)[✖](red)[✖](red)' 
