format = """$username$hostname $directory$character"""
right_format = '$cmd_duration'

add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 1
truncate_to_repo = false 
style = 'bold purple'
fish_style_pwd_dir_length = 0
format = '[$path]($style)[$read_only]($read_only_style)[\]](bold red)'

[character]
error_symbol = '\$' 
success_symbol = '\$' 

[username]
format = '[\[](bold red)[$user]($style)[@](green)'
show_always = true

[hostname]
ssh_only = false
ssh_symbol = '🌐 '
trim_at = '.'
format = '[$ssh_symbol$hostname]($style)'
style = 'bold blue'
disabled = false

[cmd_duration]
format = '[$duration]($style)'

[fossil_branch]
format = '\[[$symbol$branch]($style)\]'

[gcloud]
format = '\[[$symbol$account(@$domain)(\($region\))]($style)\]'

[git_branch]
format = '\[[$symbol$branch]($style)\]'

[git_status]
format = '([\[$all_status$ahead_behind\]]($style))'

[guix_shell]
format = '\[[$symbol]($style)\]'

[hg_branch]
format = '\[[$symbol$branch]($style)\]'

[memory_usage]
format = '\[$symbol[$ram( | $swap)]($style)\]'

[meson]
format = '\[[$symbol$project]($style)\]'

[nim]
disabled = true

[nix_shell]
format = '\[[$symbol$state( \($name\))]($style)\]'

[nodejs]
disabled = true

[ocaml]
format = '\[[$symbol($version)(\($switch_indicator$switch_name\))]($style)\]'

[opa]
disabled = true

[openstack]
format = '\[[$symbol$cloud(\($project\))]($style)\]'

[os]
format = '\[[$symbol]($style)\]'

[perl]
disabled = true

[php]
disabled = true

[pijul_channel]
format = '\[[$symbol$channel]($style)\]'

[pulumi]
format = '\[[$symbol$stack]($style)\]'

[purescript]
disabled = true

[python]
disabled = true

[raku]
format = '\[[$symbol($version-$vm_version)]($style)\]'

[red]
disabled = true

[ruby]
disabled = true

[rust]
disabled = true

[scala]
disabled = true

[spack]
format = '\[[$symbol$environment]($style)\]'

[sudo]
format = '\[[as $symbol]($style)\]'

[swift]
disabled = true

[terraform]
format = '\[[$symbol$workspace]($style)\]'

[time]
format = '\[[$time]($style)\]'

[vagrant]
disabled = true

[vlang]
disabled = true

[zig]
disabled = true

[solidity]
disabled = true
