add_newline = false

[line_break]
disabled = true

[directory]
truncation_length = 1
truncate_to_repo = false 
style = 'bold blue'
fish_style_pwd_dir_length = 1

[character]
error_symbol              = '[✖✖✖](red)' 
success_symbol            = '[❯](red)[❯](yellow)[❯](green)' 
vimcmd_replace_one_symbol = '[❮❮❮](bold purple)' 	
vimcmd_replace_symbol     = '[❮❮❮](bold purple)' 	
vimcmd_symbol             = '[](red)' 
vimcmd_visual_symbol      = '[](yellow)' 
