[colors.bright]
black = "#586e75"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#d33682"
red = "#dc322f"
white = "#fdf6e3"
yellow = "#b58900"

[colors.normal]
black = "#002b36"
blue = "#268bd2"
cyan = "#2aa198"
green = "#859900"
magenta = "#6c71c4"
red = "#cb4b16"
white = "#eee8d5"
yellow = "#b58900"

[colors.primary]
background = "#002b36"
foreground = "#839496"
