import = ["/home/victoria/.config/alacritty/themes/catppuccin-mocha.toml"]
live_config_reload = true

[colors]
draw_bold_text_with_bright_colors = true

[font]
size = 8

[font.bold]
family = "JetBrains Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrains Mono"
style = "BoldItalic"

[font.italic]
family = "JetBrains Mono"
style = "MediumItalic"

[font.normal]
family = "JetBrains Mono"
style = "Medium"

[[keyboard.bindings]]
action = "Copy"
key = "C"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0003"
key = "C"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "Paste"
key = "V"
mods = "Control"

[[keyboard.bindings]]
chars = "\u0016"
key = "V"
mods = "Control|Shift"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Control"

[scrolling]
history = 10000
multiplier = 3

[selection]
save_to_clipboard = false

[shell]
program = "fish"

[window]
opacity = 0.95

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.padding]
x = 5
y = 5
